application: webapp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: main.app
- url: /maps
  script: main.app
- url: /list
  script: main.app
- url: /results
  script: main.app
- url: /image
  static_dir: image

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"